import{a as d,S as p,i as o}from"./assets/vendor-D1AWmRWP.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();function y(a){return d.get("https://pixabay.com/api/",{params:{key:"55675156-ffdab1c2989aae756b068d836",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data)}const n=document.querySelector(".gallery");let g=new p(".gallery a");const c=document.querySelector(".loader");function f(a){const t=a.map(({webformatURL:l,largeImageURL:s,tags:e,likes:r,views:i,comments:m,downloads:u})=>`
    <li class="gallery-item">
        <a class="gallery-item-media" href="${s}"><img class="gallery-item-img" src="${l}" alt="${e}" title=""></a>
        <div class="gallery-item-description">
            <div class="gallery-item-param"><h3 class="gallery-item-property">Likes</h3><p class="gallery-item-value">${r}</p></div>
            <div class="gallery-item-param"><h3 class="gallery-item-property">Views</h3><p class="gallery-item-value">${i}</p></div>
            <div class="gallery-item-param"><h3 class="gallery-item-property">Comments</h3><p class="gallery-item-value">${m}</p></div>
            <div class="gallery-item-param"><h3 class="gallery-item-property">Downloads</h3><p class="gallery-item-value">${u}</p></div>
        </div>
    </li>
        `).join("");n.innerHTML=t,g.refresh()}function h(){n.innerHTML=""}function v(){c.classList.add("is-open")}function b(){c.classList.remove("is-open")}const L=document.querySelector(".form");L.addEventListener("submit",w);function w(a){a.preventDefault();const t=a.target.elements["search-text"].value.trim();t&&(h(),v(),y(t).then(({hits:l})=>{if(l.length===0){o.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter",backgroundColor:"#cb534a"});return}f(l)}).catch(()=>{o.show({message:"Something went wrong. Please try again later.",position:"topCenter",backgroundColor:"#cb534a"})}).finally(()=>{b()}))}
//# sourceMappingURL=index.js.map
